'use client';

/**
 * The SGBD catalogue: what each module can do, in the operator's language.
 *
 * This is `ecu-data/*.json`, generated by tools/gen_from_dump.py from the real
 * SGBD via EdiabasLib's virtual jobs. Job names, argument names and order, job
 * comments and the fault-text table are authentic ECU data; the ja/en labels
 * are translated from the German originals, which are kept alongside.
 *
 * WHY THIS EXISTS SEPARATELY FROM @tsunagi/ds2-mss54:
 *
 * There are two catalogues here and they do NOT join, so pretending otherwise
 * would be a lie the UI tells:
 *
 *   - This one is JOB-shaped (STATUS_DIGITAL, STEUERN_AVANOS1, ...). It covers
 *     all three modules and carries the names a person recognises. What it does
 *     NOT carry is how to actually build the request — the SGBD assembles most
 *     of those from arguments at run time, which a static scrape cannot recover
 *     (DSC has no unambiguous telegram at all).
 *
 *   - ds2-mss54 is BLOCK-shaped (selection 3 offset 0 = n). It is what can
 *     actually be read today, and only for MSS54.
 *
 * So the datalog reads blocks, and these views list jobs. Both are shown; what
 * is not shown is a made-up correspondence between them.
 */

export interface CatalogParam {
    id: string;
    ja: string;
    en: string;
    type?: string;
    /** The SGBD job that returns this result. */
    job?: string;
    /** The result name carrying the unit, which only the ECU can fill in. */
    unitRes?: string;
    desc?: { de?: string; ja?: string; en?: string };
}

export interface CatalogGroup {
    key: string;
    ja: string;
    en: string;
    params: CatalogParam[];
}

export interface CatalogJob {
    id: string;
    ja: string;
    en: string;
    /** Present on actuators: adaptation vs reset etc. */
    cat?: string;
    catJa?: string;
    catEn?: string;
    desc?: { de?: string; ja?: string; en?: string };
    args?: Array<{ name: string; type?: string; comment?: string }>;
}

export interface CatalogFault {
    de: string;
    ja: string;
    en: string;
}

export interface EcuCatalog {
    id: string;
    name: string;
    name_en: string;
    sgbd: string;
    /** DS2 slave address, from the SGBD. */
    address: number;
    liveCount: number;
    groups: CatalogGroup[];
    /** Persistent-write jobs: ADAPTION / RESET / LOESCHEN / SCHREIBEN. */
    actuators: CatalogJob[];
    /** Temporary, reversible actuation: STEUERN_* / IO_STATUS_* / DRUCK*. */
    testJobs: CatalogJob[];
    faultText: CatalogFault[];
    jobCount: number;
}

export interface EcuIndexEntry {
    id: string;
    name: string;
    name_en: string;
    sgbd: string;
    live: number;
    act: number;
    test: number;
    jobs: number;
}

const cache = new Map<string, EcuCatalog>();

export async function loadEcuIndex(): Promise<EcuIndexEntry[]> {
    const res = await fetch('./ecu-data/index.json', { cache: 'no-store' });
    if (!res.ok) throw new Error(`Could not load the ECU index (HTTP ${res.status})`);
    return res.json();
}

export async function loadEcuCatalog(id: string): Promise<EcuCatalog> {
    const cached = cache.get(id);
    if (cached) return cached;
    const res = await fetch(`./ecu-data/${id}.json`, { cache: 'no-store' });
    if (!res.ok) throw new Error(`Could not load the catalogue for ${id} (HTTP ${res.status})`);
    const catalog = (await res.json()) as EcuCatalog;
    cache.set(id, catalog);
    return catalog;
}

/**
 * Risk classification for a job.
 *
 * Ported from the old app's ecu-generic.js, with one change it should have had:
 * the old version hardcoded `risk: "medium"` for EVERY calibration, so a
 * harmless read (ABGLEICHWERTE_LESEN) and a coding write (CODIERDATEN_SCHREIBEN,
 * SG_RESET — "Adaptationen/FS nicht gesichert!") carried the identical pill and
 * the identical single-checkbox gate. Writes are classified here too.
 *
 * This is still name-matching, which is a heuristic. It decides how loudly to
 * warn, never whether something may run — that is the ledger's job, and the
 * ledger is default-deny.
 */
export type Risk = 'low' | 'medium' | 'high';

export function jobRisk(id: string): Risk {
    const n = id.toUpperCase();
    // Reads are reads.
    if (/_LESEN$|^STATUS_|^IO_STATUS_LESEN$/.test(n)) return 'low';

    // Forces an arbitrary output pin; DSC_SIM_* latches and has no observed
    // release job; the DSC hydraulic set drives the brake modulator, and the
    // SGBD itself warns the pump does not auto-stop (60 s max, relief valve
    // opens at 100 bar and degrades the pump).
    if (n === 'IO_STATUS_VORGEBEN') return 'high';
    if (n.startsWith('DSC_SIM_')) return 'high';
    if (/^(DRUCKABBAU|DRUCKAUFBAU|DRUCKHALTEN|PUMPENFOERDERLEISTUNG|ABS_REGELSIMULATION|NA_ENTLUEFTUNG|ENTLUEFTUNG_SERVICE)/.test(n))
        return 'high';

    // Anything that writes or resets persistent state.
    if (/_SCHREIBEN$|_LOESCHEN$|^SG_RESET$|^CODIERDATEN|^ABGLEICH|^ADAPT|^INITIALISIER|^DDS_RESET$|^EDIC_RESET$/.test(n))
        return 'high';

    // Injectors, coils, starter and fuel pump: firing these with the engine
    // running is a different proposition from firing them with it stopped, and
    // the old app gave them nothing but a voltage checkbox.
    if (/^STEUERN_(EV|ZS)\d|^STEUERN_START$|^STEUERN_EKP$/.test(n)) return 'high';

    return 'medium';
}

/** Preconditions the operator must confirm. Measured checks come later (plan §4-4). */
export function jobPreconditions(id: string): string[] {
    const risk = jobRisk(id);
    const n = id.toUpperCase();
    const conds = ['voltage_ok'];
    if (risk === 'high') conds.push('stationary');
    if (/^STEUERN_(EV|ZS)\d|^STEUERN_START$|^STEUERN_EKP$/.test(n) || /_SCHREIBEN$|^SG_RESET$/.test(n))
        conds.push('engine_off');
    return conds;
}

/**
 * How a test job is driven.
 *
 * `hold` jobs stay energised until stopped, which is why the arming state must
 * not live only in the DOM. `pulse-unreleasable` is worse: DSC_SIM_* latches
 * after actuation and no release job is visible in the SGBD, so the UI must not
 * imply it can be undone.
 */
export type ExecStyle = 'pulse' | 'hold' | 'pulse-unreleasable';

export function execStyle(job: CatalogJob): ExecStyle {
    if (job.id.startsWith('DSC_SIM_')) return 'pulse-unreleasable';
    if (job.id === 'IO_STATUS_VORGEBEN') return 'hold';
    if ((job.args ?? []).some((a) => (a.name ?? '').toUpperCase() === 'SCHALTEN')) return 'hold';
    return 'pulse';
}

export function label(item: { ja: string; en: string }, lang: 'ja' | 'en'): string {
    return (lang === 'en' ? item.en : item.ja) || item.ja || item.en;
}

export function description(
    item: { desc?: { de?: string; ja?: string; en?: string } },
    lang: 'ja' | 'en',
): { text: string; original: string } {
    const d = item.desc;
    return {
        text: (lang === 'en' ? d?.en : d?.ja) || d?.de || '',
        // The German original is always shown alongside. The ja/en are machine
        // translations of it, and a confident mistranslation of an actuator
        // name is an operating hazard, not a cosmetic one.
        original: d?.de || '',
    };
}
