'use client';

/**
 * The SGBD catalogue: every job each module has, in the operator's language.
 *
 * This is `ecu-data/<id>.jobs.json`, schema 2, generated by tools/gen_ecu_data.py
 * from the real SGBD via EdiabasLib's virtual jobs. Job names, argument names and
 * order, result names, job comments, the fault table and the ECU's own status
 * vocabularies are authentic ECU data; the ja/en labels are translated from the
 * German originals, which are kept alongside and always shown.
 *
 * ## What changed in schema 2, and why it matters
 *
 * Schema 1 shipped 131 of 323 jobs and ZERO results. The regexes that dropped the
 * other 192 lived here as well as in the generator, so the same job id was
 * classified three times by three different rules — `ABGLEICHWERTE_LESEN` was a
 * "persistent write" to the generator, `low` risk to `jobRisk`, and a `read` to
 * `jobOps`. Three answers, at most one of them right.
 *
 * So classification now happens exactly once, in `tools/sgbd/classify.py`, and is
 * baked into the data. **This module reads. It does not derive.** If a fact about
 * a job is not in the JSON, the answer is that we do not know it — not that we
 * can guess it from the name here.
 *
 * ## WHY THIS EXISTS SEPARATELY FROM @tsunagi/ds2-mss54
 *
 * There are two catalogues and they do NOT join, so pretending otherwise would be
 * a lie the UI tells:
 *
 *   - This one is JOB-shaped (STATUS_DIGITAL, STEUERN_AVANOS1, ...). It covers all
 *     three modules and carries the names a person recognises. What it does NOT
 *     carry is how to build the request — the SGBD assembles most of those from
 *     arguments at run time, which a static scrape cannot recover (DSC has no
 *     unambiguous telegram at all).
 *
 *   - ds2-mss54 is BLOCK-shaped (selection 3 offset 0 = n). It is what can
 *     actually be read today, and only for MSS54.
 *
 * So the datalog reads blocks and these views list jobs. Both are shown; what is
 * not shown is a made-up correspondence between them.
 */

import { humanName, type HumanName } from '@/components/ui';

export type { HumanName };

// ---------------------------------------------------------------------------
// The vocabularies. These mirror tools/sgbd/classify.py exactly — if one side
// gains a member the other must too, which is what `assertKnownVocabulary` is
// for at load time.
// ---------------------------------------------------------------------------

/** What kind of thing this operation is. */
export type JobClass =
    /** Reads. Nothing about the car changes. */
    | 'read'
    /** Actuates temporarily; when it ends, the car is as it was. */
    | 'test'
    /** Rewrites learned or adjusted values. */
    | 'calibration'
    /** Vehicle coding — the equipment configuration. */
    | 'coding'
    /**
     * The values that say which car this is: VIN, order and manufacturing data, the
     * immobiliser's key material, the odometer.
     *
     * Not `calibration` — nothing here was learned. Not `coding` — this is not the
     * equipment list. Not `programming` — the program area is untouched. The class exists
     * because without it the generic `_SCHREIBEN` rule filed all 43 of them as calibration
     * addressed to the OWNER, so EWS3's `ISN_SCHREIBEN` (the immobiliser secret) and
     * `FGNR_SCHREIBEN` (the chassis number) were listed for a car's owner under the
     * sentence "rewrites a learned or adjusted value". That sentence was not true of them.
     */
    | 'identity'
    /** Flash / EEPROM / inspection stamp. WinKFP territory; this app does not run it. */
    | 'programming'
    /** A step inside another job's procedure. Meaningless on its own. */
    | 'protocol'
    /**
     * The SGBD says nothing about it, so neither do we.
     *
     * This is a real answer and it is load-bearing. The generator used to call these `read`,
     * on the reasoning that read is the safe thing to be — which put EWS3's VIN write and the
     * coding writes into the same class as reading a coolant temperature, and past the first
     * gate in `mayRun`. Not knowing what a job does is not evidence that it is harmless.
     */
    | 'unclassified';

/** Who this is for. Not everything in an ECU is addressed to a car's owner. */
export type Audience = 'owner' | 'technician' | 'protocol';

/**
 * Who carries the operation forward once it has started.
 *
 * Separate from `termination` on purpose: SMG II's test program 0x02 (clutch bite
 * point) is driven by the ECU *and* requires a human to hold the engine running.
 * One axis cannot say both.
 */
export type Actor =
    /** The ECU runs it by itself. */
    | 'ecu'
    /** The app must keep sending, or the actuation drops. */
    | 'app'
    /** A person must physically do something. */
    | 'operator'
    /** The car has to be driven. */
    | 'driver';

/** How it ends. */
export type Termination =
    /** It finishes on its own. */
    | 'self'
    /** The app stops it. */
    | 'app-stop'
    /** A differently-named job stops it. */
    | 'companion-job'
    /** It does not stop. Latching. */
    | 'none';

/** Where the answer appears. */
export type ResultDelivery = 'inline' | 'companion-job' | 'live-block' | 'none';

export type Risk = 'low' | 'medium' | 'high';

/**
 * How confident we are, and why.
 *
 * `name-heuristic` is the weakest and the UI prints it. A classification derived
 * from a job's name is a guess about a name, and the reader is entitled to know
 * that is what they are looking at.
 */
export type Provenance = 'sgbd-comment' | 'sgbd-args' | 'name-heuristic' | 'authored';

/**
 * What a result IS, not what it is called.
 *
 * The SGBD returns `X_WERT` / `X_EINH` / `X_TEXT` as three flat siblings; they are
 * one logical row. Schema 1 threw the `_EINH` and `_TEXT` away, which discarded
 * both the unit (so a number had no dimension) and — worse —
 * `LESEN_SYSTEMCHECK_DMTL_TEXT`, the ECU's own plain-language verdict on the tank
 * leak test. That is the single most owner-facing string in the dataset.
 */
export type ResultRole = 'value' | 'unit' | 'text' | 'status' | 'telegram' | 'raw';

/** How an argument is supplied. */
export type ArgKind = 'enum' | 'number' | 'text' | 'flag' | 'unknown';

/**
 * The runtime allowlists, derived from the types so they CANNOT fall behind them.
 *
 * They were plain arrays annotated `readonly JobClass[]`, which type-checks a subset happily.
 * So when `unclassified` was added to JobClass the array kept six entries, the compiler said
 * nothing, and `assertLoadable` rejected 41 of the 51 shipped modules at load — every one that
 * has a job the SGBD says nothing about. It went unnoticed because the tests and the manual
 * check all use mss54 / smg2 / dsc_e46, which are three of the ten modules with no such job.
 *
 * `Record<JobClass, true>` is exhaustive: adding a member to the union without adding it here
 * is a compile error, which is the only version of this that stays true.
 */
const JOB_CLASSES = Object.keys({
    read: true,
    test: true,
    calibration: true,
    coding: true,
    identity: true,
    programming: true,
    protocol: true,
    unclassified: true,
} satisfies Record<JobClass, true>) as readonly JobClass[];

const AUDIENCES = Object.keys({
    owner: true,
    technician: true,
    protocol: true,
} satisfies Record<Audience, true>) as readonly Audience[];

// ---------------------------------------------------------------------------
// Shapes
// ---------------------------------------------------------------------------

/**
 * An index into `EcuProfile.texts`, not a string.
 *
 * 2311 results carry 1555 distinct names and 1010 distinct comments in three
 * languages. Inlining them makes the three files ~3.5x larger; interning makes
 * them ~1.6x. These are fetched per module switch off a static host.
 */
export type TextRef = number;

export interface LocalisedText {
    /** The SGBD original. Always kept — a confident mistranslation of an actuator name is an operating hazard. */
    de: string;
    ja: string;
    en: string;
}

/**
 * A value range the SGBD states in its own comment.
 *
 * `default` is the FACTORY DEFAULT, not a target. A learned value like
 * `KUPPL_SCHLEIF_PKT_INK_WERT` (the clutch bite point) diverging from it is
 * normal and expected. Rendering it as "the target" would be a lie on exactly the
 * values that matter most, so the verdict this supports is only "inside the
 * stated range or not".
 */
export interface ValueSpec {
    min?: number;
    max?: number;
    /** Factory default. NOT a target. */
    default?: number;
    /** A fixed value the SGBD states with `Immer:` — there is no range. */
    always?: number;
    unit?: string;
    /** The German sentence it was parsed out of. Shown, so the parse can be checked. */
    source?: TextRef;
    provenance: 'sgbd-comment';
}

/**
 * A constraint between two fields, which is not the same thing as a range.
 *
 * `Hinweis: Differenz AK zu EK ist min.: 430 Ink, max.: 590` constrains
 * `POS_EINKUP_WERT - POS_AUSKUP_WERT`. Storing it as a range on either field
 * alone would flag a perfectly good clutch.
 */
export interface CrossFieldConstraint {
    between: string[];
    relation: 'difference';
    min?: number;
    max?: number;
    unit?: string;
    source?: TextRef;
    provenance: 'sgbd-comment';
}

/**
 * Which argument values make this result meaningful.
 *
 * `ADAPTIONSWERTE_LESEN` declares 216 results but returns roughly 30 of them:
 * `ADAPTION_LESEN` picks clutch (0), gearbox (1) or gearbox data (2). The SGBD
 * does not state the partition machine-readably, so `provenance` says `inferred`
 * and the UI must not present the filtered list as certain.
 */
export interface WhenArg {
    arg: string;
    values: string[];
    provenance: 'inferred';
}

export interface CatalogArg {
    name: string;
    type: string;
    kind: ArgKind;
    comment?: TextRef;
    /** Real choices from an SGBD table. Absent means free entry — never invent options. */
    options?: Array<{ value: string; note?: string }>;
    /**
     * Which table the choices came from, and what the SGBD said that made it the
     * right table. `dropped` lists rows deliberately not offered, with the reason
     * — a list that is silently shorter than its source is how things disappear.
     *
     * `table` is absent when the SGBD enumerated the values in the argument's own
     * comment rather than in a table (four arguments do). No table name is
     * invented for those; the absence is what the UI reads.
     */
    optionsFrom?: { table?: string; why: string; dropped?: string[] };
}

export interface CatalogResult {
    name: string;
    type: string;
    role: ResultRole;
    comment?: TextRef;
    /** For `unit` / `text` roles: the name of the value result they belong to. */
    valueOf?: string;
    /** For `value` roles: the sibling carrying the unit / the ECU's plain-language verdict. */
    unitRes?: string;
    textRes?: string;
    whenArg?: WhenArg;
    spec?: ValueSpec;
}

export interface JobOperationData {
    kind: OpKind;
    actor: Actor;
    termination: Termination;
    resultDelivery: ResultDelivery;
    /** Jobs the SGBD says must be sent first, or the ECU refuses. */
    prerequisiteJobs?: string[];
    stopJob?: string;
    /**
     * When stopping means sending the SAME job with different arguments.
     *
     * `STEUERN_STELLGLIED` is switched off with `STEUERART1 = INAKTIV` — one of
     * the four values the SGBD lists for that argument, and what INPA sends to
     * stop the hydraulic pump. It used to be recorded as `stopJob: 'INAKTIV'`,
     * which named a job that does not exist.
     */
    stopArgs?: Record<string, string>;
    /** For `resultDelivery: 'companion-job'`: the job that reads the answer. */
    resultJob?: string;
    /** The ECU's own session timeout. A SAFETY property: it bounds the damage if the browser dies mid-actuation. */
    ecuTimeoutSec?: number;
    /** The longest the ECU holds an output, even with keep-alive. */
    maxHoldSec?: number;
    irreversible?: string;
    provenance: Provenance;
}

export interface CatalogJob {
    id: string;
    ja: string;
    en: string;
    class: JobClass;
    audience: Audience;
    /** Which system of the car. `'unknown'` is a stated answer, not a gap. */
    system: string;
    risk: Risk;
    riskProvenance: Provenance;
    op: JobOperationData;
    /** Keys the operator must confirm before anything is sent. */
    preconditions: string[];
    args: CatalogArg[];
    results: CatalogResult[];
    desc?: TextRef;
    crossFieldConstraints?: CrossFieldConstraint[];
    /** A sentence about this specific job, written by hand where a rule could not say it. */
    note?: string;
}

/** A fault, keyed by the code the ECU actually reports. */
export interface CatalogFault {
    code: string;
    text: TextRef;
    /** Which freeze-frame fields are meaningful for this fault (MSS54 only). */
    env?: string[];
}

/**
 * One freeze-frame field, with the arithmetic to turn a byte into a measurement.
 *
 * Without this the diagnosis pane printed `20 40 60 80`. With it, `0x00` scaled by
 * 40 is engine speed in 1/min.
 */
export interface EnvField {
    code: string;
    text: TextRef;
    unit?: string;
    scale?: number;
    add?: number;
    type?: string;
}

/** A status code the ECU returns, and what the ECU itself calls it. */
export interface VocabEntry {
    code: string;
    text: TextRef;
    /** BRK = aborted, WAIT = waiting, STATE = in progress, RSLT = verdict. */
    cond?: string;
}

export interface EcuProfile {
    schema: 2;
    id: string;
    name: string;
    name_en: string;
    sgbd: string;
    /** DS2 slave address, from the SGBD. */
    address: number;
    /** Whether any of this has been confirmed against a real car. */
    verified: boolean;
    generatedFrom: {
        dump: string;
        dumpSha256: string;
        generator: string;
        generatedAt: string;
    };
    jobCount: number;
    texts: LocalisedText[];
    jobs: CatalogJob[];
    faultText: CatalogFault[];
    envFields: EnvField[];
    /**
     * The ECU's own words for its status codes.
     *
     * `tevstatus` / `slsstatus` / `ldpstatus` are the SYSTEMCHECK verdicts — the
     * literal answer to "how do I know it is OK" for the tank-leak, secondary-air
     * and purge-valve tests. These were budgeted as hand-written copy until the
     * refreshed dump showed the ECU shipping them.
     */
    vocabularies: Record<string, VocabEntry[]>;
    source: string;
}

export interface EcuIndexEntry {
    id: string;
    name: string;
    name_en: string;
    sgbd: string;
    address: number;
    addressHex: string;
    /** Which selector optgroup this module sits in. Keys are defined by `EcuIndex.groups`. */
    group: string;
    /** Which cars have it. Two modules can share an address and differ only here — 0x56 is
     *  ASCMK20 on an early car and DSC_E46 on a later one, and they are never both fitted. */
    fit: string;
    note: string;
    note_en: string;
    /** What the ECU calls itself in its own INFO job, e.g.
     *  "ABS/ASC, ITT_Industries, MK20E_I, E36,E46". Empty when no trace was ever taken from
     *  the module, which is itself worth showing: the address is then a declaration, not a
     *  measurement. */
    ecuDesc: string;
    jobs: number;
    results: number;
    faults: number;
    envFields: number;
    byClass: Partial<Record<JobClass, number>>;
    /**
     * The extra files that exist beside `<id>.jobs.json`, by NAME.
     *
     * Names rather than suffixes because one of them is spelt differently
     * (`smg2-workflows.json`), and a rule with an exception in it is a rule someone gets
     * wrong. Fetching only what is listed is what stops 51 modules producing a hundred
     * avoidable 404s a session — `mss54.hydraulics.json` was being requested on every load
     * and has never existed.
     */
    sidecars: string[];
}

/**
 * The index, as an object rather than a bare array.
 *
 * It was an array, which left nowhere to put the schema number, the generation time, or the
 * group and fitment tables — so a reader had only "it is an array" to go on, and the selector
 * had to carry its own copy of the group labels.
 */
export interface EcuIndex {
    schema: number;
    generatedAt: string;
    groups: { key: string; ja: string; en: string }[];
    fit: Record<string, { ja: string; en: string }>;
    modules: EcuIndexEntry[];
}

/** Re-exported so `jobOps` stays the one place that names the operation shapes. */
import type { OpKind } from './jobOps';
export type { OpKind };

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

const cache = new Map<string, EcuProfile>();

export async function loadEcuIndex(): Promise<EcuIndex> {
    const res = await fetch('./ecu-data/index.json', { cache: 'no-store' });
    if (!res.ok) throw new Error(`Could not load the ECU index (HTTP ${res.status})`);
    const index = (await res.json()) as EcuIndex;
    // A schema check at the door, not a crash three screens later. The array form has no
    // `modules`, so this is also what an old cached index fails on.
    if (!Array.isArray(index?.modules)) {
        throw new Error('The ECU index is not in the expected shape (schema 2 object).');
    }
    return index;
}

export async function loadEcuCatalog(id: string): Promise<EcuProfile> {
    const cached = cache.get(id);
    if (cached) return cached;
    const res = await fetch(`./ecu-data/${id}.jobs.json`, { cache: 'no-store' });
    if (!res.ok) throw new Error(`Could not load the catalogue for ${id} (HTTP ${res.status})`);
    const profile = (await res.json()) as EcuProfile;
    assertLoadableProfile(profile);
    cache.set(id, profile);
    return profile;
}

/**
 * Load-time invariants. A wrong shape must fail here, once, and not as a blank
 * cell somewhere in the UI an hour later.
 *
 * The job-count check is the one that was missing: schema 1 dropped 192 jobs
 * silently because nothing ever compared what was emitted against what the dump
 * declared.
 */
/** Exported so a test can put every shipped profile through it. It was private, and the
 *  consequence was that the only profiles ever checked were the three the tests name —
 *  which are three of the ten that happened to pass. See shippedData.test.ts. */
export function assertLoadableProfile(p: EcuProfile): void {
    if (p.schema !== 2) throw new Error(`${p.id}: expected schema 2, got ${p.schema}`);
    if (p.jobs.length !== p.jobCount)
        throw new Error(`${p.id}: ${p.jobs.length} jobs in a file declaring ${p.jobCount}`);
    for (const j of p.jobs) {
        if (!JOB_CLASSES.includes(j.class)) throw new Error(`${p.id}.${j.id}: unknown class ${j.class}`);
        if (!AUDIENCES.includes(j.audience)) throw new Error(`${p.id}.${j.id}: unknown audience ${j.audience}`);
    }
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

export function label(item: { ja: string; en: string }, lang: 'ja' | 'en'): HumanName {
    return humanName((lang === 'en' ? item.en : item.ja) || item.ja || item.en);
}

/**
 * Resolve an interned text.
 *
 * Returns the German original alongside the translation, always. The ja/en are
 * machine translations, and the German is the only text with an ECU behind it.
 */
export function text(
    p: EcuProfile,
    ref: TextRef | undefined,
    lang: 'ja' | 'en',
): { text: HumanName; original: string } {
    const none = { text: humanName(''), original: '' };
    if (ref === undefined) return none;
    const t = p.texts[ref];
    if (!t) return none;
    return { text: humanName((lang === 'en' ? t.en : t.ja) || t.de), original: t.de };
}

/** The job's own description, resolved. */
export function description(p: EcuProfile, job: CatalogJob, lang: 'ja' | 'en') {
    return text(p, job.desc, lang);
}

/**
 * The risk for a job. It is data now.
 *
 * Kept as a function rather than inlining `job.risk` at every call site so the
 * places that decide how loudly to warn stay greppable — and so the fact that
 * this NEVER decides whether something may run stays documented. That is the
 * ledger's job, and the ledger is default-deny.
 */
export function jobRiskOf(job: CatalogJob): Risk {
    return job.risk;
}

/** Index jobs by id, for the companion/prerequisite/stop lookups the detail view needs. */
export function jobIndex(p: EcuProfile): Map<string, CatalogJob> {
    return new Map(p.jobs.map((j) => [j.id, j]));
}

/**
 * The results that actually come back for a given set of argument values.
 *
 * A result with no `whenArg` is always returned. One with a `whenArg` is returned
 * only for the listed values — and when the operator has not chosen a value yet,
 * it is included, because hiding a row on the grounds of a choice nobody has made
 * is worse than showing one that may not appear.
 */
export function resultsFor(job: CatalogJob, argValues: Record<string, string>): CatalogResult[] {
    return job.results.filter((r) => {
        if (!r.whenArg) return true;
        const chosen = argValues[r.whenArg.arg];
        if (chosen === undefined || chosen === '') return true;
        return r.whenArg.values.includes(chosen);
    });
}

/** Does this result set carry anything with a stated range? Drives whether the calibration block renders at all. */
export function hasSpecs(job: CatalogJob): boolean {
    return job.results.some((r) => r.spec) || (job.crossFieldConstraints?.length ?? 0) > 0;
}

/**
 * Where a value sits against the range the SGBD states.
 *
 * `'unknown'` when there is no stated range — which is the honest answer for
 * every MSS54 and DSC adaptation, because the SGBD publishes no limits for them.
 * The UI shows that as a first-class state, not as a blank.
 */
export type SpecVerdict = 'in-range' | 'out-of-range' | 'unknown';

export function verdictFor(spec: ValueSpec | undefined, value: number | undefined): SpecVerdict {
    if (!spec || value === undefined || !Number.isFinite(value)) return 'unknown';
    if (spec.always !== undefined) return value === spec.always ? 'in-range' : 'out-of-range';
    if (spec.min === undefined && spec.max === undefined) return 'unknown';
    if (spec.min !== undefined && value < spec.min) return 'out-of-range';
    if (spec.max !== undefined && value > spec.max) return 'out-of-range';
    return 'in-range';
}

// ---------------------------------------------------------------------------
// Facets
// ---------------------------------------------------------------------------

export interface FacetCount<T extends string = string> {
    key: T;
    count: number;
}

/**
 * Counts per facet value, over the WHOLE catalogue — not over what is currently
 * shown.
 *
 * Showing counts of the filtered set makes hidden things invisible twice. With
 * 323 jobs behind a default filter, the count is the only thing telling a reader
 * that there is more here than they are looking at.
 */
export function facetCounts<K extends string>(jobs: CatalogJob[], of: (j: CatalogJob) => K): FacetCount<K>[] {
    const m = new Map<K, number>();
    for (const j of jobs) m.set(of(j), (m.get(of(j)) ?? 0) + 1);
    return [...m.entries()].map(([key, count]) => ({ key, count })).sort((a, b) => b.count - a.count);
}
