// ============================================================================
//  GENERATED FILE — do not edit by hand.
//  Regenerate with: python tools/gen_live_blocks.py
// ============================================================================
//
//  MSS54 live-measurement block layouts: offsets, formats, scaling.
//  8 blocks, 213 fields.
//
//  A block is read with DS2 control 0x0B (READ_IO_STATUS) plus the selection
//  byte, e.g. selection 35 (VANOS) is `12 05 0B 23 3F`. The whole block comes
//  back in one response and every field below is an offset into that payload.
//
//  PROVENANCE: derived from the decompiled DmeLiveValueCatalog.cs of a
//  third-party tool. Byte offsets and scaling are arguably facts about the
//  ECU rather than creative expression, but the route by which they were
//  obtained is a decompilation — see THIRD-PARTY-NOTICES.md §3.
//
//  NOT VERIFIED ON A VEHICLE. `expectedLength` below is the reference's
//  declared block length and is advisory only: validate a response against
//  minPayloadLength(fields) instead, because a declared length can be stale
//  while the field table is not (the reference contains exactly that case).
// ============================================================================

import type { FieldDef } from '@tsunagi/ds2-core';

export interface LiveValueField extends FieldDef {
    /** Human-readable name from the reference catalog. */
    name: string;
    unit: string;
    group: string;
}

export interface LiveValueBlock {
    /** Selection byte sent with DS2 control 0x0B. */
    selection: number;
    name: string;
    group: string;
    /** The reference's declared length. Advisory — see the header note. */
    expectedLength: number;
    fields: readonly LiveValueField[];
}

export const MSS54_LIVE_BLOCKS: readonly LiveValueBlock[] = [
    {
        selection: 2,
        name: "A/D Converters",
        group: "Analog Inputs",
        expectedLength: 64,
        fields: [
            { symbol: "UINTOUT1", name: "Knock signal multiplex channel 1/2", offset: 0, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UINTOUT2", name: "Knock signal multiplex channel 3/4", offset: 2, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UISERVO", name: "Servotronic valve shunt voltage", offset: 4, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UHFM1", name: "Air mass meter 1", offset: 6, format: 'uint10', scale: 0.00564, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UHFM2", name: "Air mass meter 2", offset: 8, format: 'uint10', scale: 0.00564, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UTDME", name: "ECU temperature sensor", offset: 10, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UEDKPM", name: "Throttle sensor master", offset: 12, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UTABG", name: "Exhaust temperature sensor", offset: 14, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UDKG1M", name: "Throttle position sensor 1 master", offset: 16, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UPWG1M", name: "Pedal sensor channel 1 master", offset: 18, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UPWG2M", name: "Pedal sensor channel 2 master", offset: 20, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UEXT1", name: "Sensor supply 1", offset: 22, format: 'uint10', scale: 0.009766, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UEXT2", name: "Sensor supply 2", offset: 24, format: 'uint10', scale: 0.009766, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UPUMG", name: "Ambient pressure sensor", offset: 26, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UTANS", name: "Intake air temperature sensor", offset: 28, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UTMOT", name: "Coolant temperature sensor", offset: 30, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UPWG1S", name: "Pedal sensor 1 slave", offset: 32, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UEDKPS", name: "Throttle sensor slave", offset: 34, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UDKG1S", name: "Throttle position sensor 1 slave", offset: 36, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UTKA", name: "Radiator outlet temperature sensor", offset: 38, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UIDMTL", name: "Leak diagnosis pump shunt voltage", offset: 40, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UGEN", name: "Pulsed fuel pump diagnostic voltage", offset: 42, format: 'uint10', scale: 0.009766, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UUBHR", name: "Main relay vehicle voltage", offset: 44, format: 'uint10', scale: 0.024923999999999998, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSV1", name: "Oxygen sensor 1 before catalyst", offset: 46, format: 'uint10', scale: 0.001088, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSV2", name: "Oxygen sensor 2 before catalyst", offset: 48, format: 'uint10', scale: 0.001088, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSN1", name: "Oxygen sensor 1 after catalyst", offset: 50, format: 'uint10', scale: 0.001088, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSN2", name: "Oxygen sensor 2 after catalyst", offset: 52, format: 'uint10', scale: 0.001088, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSHV1", name: "Oxygen sensor heater 1 before catalyst", offset: 54, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSHV2", name: "Oxygen sensor heater 2 before catalyst", offset: 56, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSHN1", name: "Oxygen sensor heater 1 after catalyst", offset: 58, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "ULSHN2", name: "Oxygen sensor heater 2 after catalyst", offset: 60, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
            { symbol: "UKFKP", name: "Map-controlled cooling actuator sensor", offset: 62, format: 'uint10', scale: 0.004883, add: 0, unit: "V", group: "Analog Inputs" },
        ],
    },
    {
        selection: 3,
        name: "Standard Measurements",
        group: "Engine",
        expectedLength: 35,
        fields: [
            { symbol: "n", name: "Engine speed", offset: 0, format: 'uint16', scale: 1, add: 0, unit: "rpm", group: "" },
            { symbol: "llr_n_soll", name: "Idle controller target speed", offset: 2, format: 'uint16', scale: 1, add: 0, unit: "rpm", group: "" },
            { symbol: "ml", name: "Total air mass", offset: 4, format: 'uint16', scale: 0.25, add: 0, unit: "kg/h", group: "" },
            { symbol: "tl", name: "Load signal", offset: 6, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "rf", name: "Relative filling", offset: 8, format: 'uint16', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "tan", name: "Intake air temperature", offset: 10, format: 'uint8', scale: 1, add: -48, unit: "°C", group: "" },
            { symbol: "tmot", name: "Engine temperature", offset: 11, format: 'uint8', scale: 1, add: -48, unit: "°C", group: "" },
            { symbol: "toel", name: "Oil temperature", offset: 12, format: 'uint8', scale: 1, add: -48, unit: "°C", group: "" },
            { symbol: "tka", name: "Radiator outlet temperature", offset: 13, format: 'uint8', scale: 1, add: -48, unit: "°C", group: "" },
            { symbol: "tabg", name: "Exhaust temperature", offset: 14, format: 'int7', scale: 16, add: 0, unit: "°C", group: "" },
            { symbol: "tumg", name: "Ambient temperature CAN", offset: 15, format: 'uint8', scale: 1, add: -48, unit: "°C", group: "" },
            { symbol: "ub", name: "Main relay vehicle voltage", offset: 16, format: 'uint8', scale: 0.1, add: 0, unit: "V", group: "" },
            { symbol: "uext1m", name: "Sensor supply 1 master", offset: 17, format: 'uint8', scale: 0.039100684261974585, add: 0, unit: "V", group: "" },
            { symbol: "uext2m", name: "Sensor supply 2 slave", offset: 18, format: 'uint8', scale: 0.039100684261974585, add: 0, unit: "V", group: "" },
            { symbol: "pumg", name: "Ambient pressure internal", offset: 19, format: 'uint8', scale: 3, add: 500, unit: "mbar", group: "" },
            { symbol: "aq_rel", name: "Relative opening cross-section", offset: 20, format: 'uint16', scale: 0.46511627906976744, add: 0, unit: "%", group: "" },
            { symbol: "wdk_zustand", name: "Throttle status", offset: 22, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "pwg1", name: "Pedal sensor 1 actual position", offset: 23, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "pwg2", name: "Pedal sensor 2 actual position", offset: 25, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "wdk1", name: "Throttle potentiometer 1 actual position", offset: 27, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "wdk2", name: "Throttle potentiometer 2 actual position", offset: 29, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "edk_soll", name: "Throttle target value", offset: 31, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "tog_level_k", name: "Corrected oil level", offset: 33, format: 'uint8', scale: 1, add: 0, unit: "mm", group: "" },
            { symbol: "tdme", name: "ECU temperature", offset: 34, format: 'uint8', scale: 1, add: -48, unit: "°C", group: "" },
        ],
    },
    {
        selection: 4,
        name: "Switch / Status Bits",
        group: "Status",
        expectedLength: 43,
        fields: [
            { symbol: "zustand_motor", name: "Engine operating state", offset: 0, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "kkos_st_treiber", name: "A/C compressor control", offset: 1, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "asc_st", name: "ASC intervention", offset: 2, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "kath_st", name: "Catalyst heating", offset: 3, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ftyp_st", name: "Driver type recognition", offset: 4, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "vmax_st", name: "Vmax limiter", offset: 5, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "slp_st", name: "Secondary air pump", offset: 6, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "slv_st", name: "Secondary air valve", offset: 7, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ekp_st", name: "Fuel pump", offset: 8, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "elu_st", name: "Electric fan", offset: 9, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "akl_stcfg_rollenbetrieb", name: "Exhaust flap / roller mode", offset: 10, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "start_status", name: "Starter relay", offset: 11, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "fgr_can_st", name: "Cruise control", offset: 12, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "lfr_zustand", name: "Idle controller", offset: 13, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "kr_st", name: "Knock controller", offset: 14, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "lshv1_st", name: "Oxygen sensor heater 1 before catalyst", offset: 15, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "lshv2_st", name: "Oxygen sensor heater 2 before catalyst", offset: 16, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "lshn1_st", name: "Oxygen sensor heater 1 after catalyst", offset: 17, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "lshn2_st", name: "Oxygen sensor heater 2 after catalyst", offset: 18, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "tz_ed_status", name: "Ignition channels", offset: 19, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ti_ausblend_ist", name: "Injection channels", offset: 20, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "sa_we_st", name: "Overrun fuel cutoff", offset: 21, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ba_st", name: "Acceleration enrichment", offset: 22, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "noise_st", name: "Noise reduction", offset: 23, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "schalt_s_st", name: "Slave switch inputs", offset: 24, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "schalter_can", name: "CAN switch inputs", offset: 25, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "mil_st", name: "MIL lamp control", offset: 26, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ews_status", name: "EWS-3 release status", offset: 27, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "dsv_st", name: "VANOS pressure accumulator valve", offset: 28, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "servo_mode", name: "Servotronic status", offset: 29, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "schalt_m_st", name: "Master switch inputs", offset: 30, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "can_n_elu", name: "CAN fan-stage request", offset: 31, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "fgr_tast_reg", name: "MFL cruise button number", offset: 32, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ds2_ti_unlock", name: "Safety unlock", offset: 33, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "oek_status", name: "Oil circuit switchover valves", offset: 34, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "la_st_ein1", name: "Lambda controller status bank 1", offset: 35, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "la_st_ein2", name: "Lambda controller status bank 2", offset: 36, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "vvdp_verbaut", name: "Pressure accumulator valve installed", offset: 37, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "kath_zustand", name: "Catalyst heating state", offset: 38, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ssp_st", name: "Suction jet pump status", offset: 39, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ldph_verbaut", name: "DMTL heater installed", offset: 40, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ldph_st", name: "DMTL heater status", offset: 41, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
            { symbol: "ssp_diag_st", name: "Suction jet pump diagnostic status", offset: 42, format: 'uint8', scale: 1, add: 0, unit: "", group: "Status" },
        ],
    },
    {
        selection: 19,
        name: "Operating Measurements",
        group: "Engine",
        expectedLength: 90,
        fields: [
            { symbol: "v", name: "Vehicle speed direct", offset: 0, format: 'uint16', scale: 1, add: 0, unit: "km/h", group: "" },
            { symbol: "v_asc", name: "Vehicle speed CAN", offset: 2, format: 'uint16', scale: 0.0625, add: 0, unit: "km/h", group: "" },
            { symbol: "ti_ausblend_ist", name: "Injection blanking counter actual", offset: 4, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ti_ausblend_soll", name: "Injection blanking counter target", offset: 5, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ti1", name: "Injection time cylinder 1", offset: 6, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "ti2", name: "Injection time cylinder 2", offset: 8, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "ti3", name: "Injection time cylinder 3", offset: 10, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "ti4", name: "Injection time cylinder 4", offset: 12, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "ti5", name: "Injection time cylinder 5", offset: 14, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "ti6", name: "Injection time cylinder 6", offset: 16, format: 'uint16', scale: 0.001, add: 0, unit: "ms", group: "" },
            { symbol: "tz1", name: "Ignition angle cylinder 1", offset: 22, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "" },
            { symbol: "tz2", name: "Ignition angle cylinder 2", offset: 24, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "" },
            { symbol: "tz3", name: "Ignition angle cylinder 3", offset: 26, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "" },
            { symbol: "tz4", name: "Ignition angle cylinder 4", offset: 28, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "" },
            { symbol: "tz5", name: "Ignition angle cylinder 5", offset: 30, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "" },
            { symbol: "tz6", name: "Ignition angle cylinder 6", offset: 32, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "" },
            { symbol: "tetv", name: "Tank ventilation valve pulse time", offset: 38, format: 'uint16', scale: 0.002, add: 0, unit: "ms", group: "" },
            { symbol: "la_f_regler1", name: "Lambda controller factor 1", offset: 40, format: 'uint16', scale: 3.0517578125e-05, add: 0, unit: "", group: "" },
            { symbol: "la_f_regler2", name: "Lambda controller factor 2", offset: 42, format: 'uint16', scale: 3.0517578125e-05, add: 0, unit: "", group: "" },
            { symbol: "lank_tv1", name: "Post-cat controller 1 tv share", offset: 44, format: 'uint16', scale: 10, add: 0, unit: "ms", group: "" },
            { symbol: "lank_tv2", name: "Post-cat controller 2 tv share", offset: 46, format: 'uint16', scale: 10, add: 0, unit: "ms", group: "" },
            { symbol: "servo_i_ist", name: "Servotronic valve current actual", offset: 48, format: 'uint16', scale: 0.89, add: 0, unit: "mA", group: "" },
            { symbol: "servo_tast", name: "Servotronic valve duty", offset: 50, format: 'uint16', scale: 0.05, add: 0, unit: "%", group: "" },
            { symbol: "servo_i_soll", name: "Servotronic valve current target", offset: 52, format: 'uint16', scale: 0.89, add: 0, unit: "mA", group: "" },
            { symbol: "elu_dreh", name: "Electric fan speed stage", offset: 54, format: 'uint8', scale: 1, add: 0, unit: "%", group: "" },
            { symbol: "ldp_i_filt", name: "Leak diagnosis pump measured current", offset: 55, format: 'uint16', scale: 0.009, add: 0, unit: "mA", group: "" },
            { symbol: "ldp_st", name: "Leak diagnosis result register", offset: 57, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ldp_i_ref", name: "Leak diagnosis reference-leak current", offset: 58, format: 'uint16', scale: 0.009, add: 0, unit: "mA", group: "" },
            { symbol: "asc_ay", name: "CAN lateral acceleration", offset: 60, format: 'int7', scale: 0.1, add: 0, unit: "m/s²", group: "" },
            { symbol: "asc_ax", name: "CAN longitudinal acceleration", offset: 61, format: 'int7', scale: 0.1, add: 0, unit: "m/s²", group: "" },
            { symbol: "tefc_ll_st", name: "Tank ventilation system test result", offset: 62, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "sls_st_bandende", name: "Secondary air system test result", offset: 63, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ldp_st_nv", name: "Nonvolatile leak diagnosis result", offset: 64, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ldp_t_mess", name: "Last leak diagnosis measuring time", offset: 65, format: 'uint16', scale: 0.1, add: 0, unit: "s", group: "" },
            { symbol: "ldp_i_ref_korr", name: "Corrected leak diagnosis reference current", offset: 67, format: 'uint16', scale: 0.009, add: 0, unit: "mA", group: "" },
            { symbol: "ldp_i_min", name: "Minimum reference current", offset: 69, format: 'uint16', scale: 0.009, add: 0, unit: "mA", group: "" },
            { symbol: "ldp_i_stabil", name: "Stable fine-leak current", offset: 71, format: 'uint16', scale: 0.009, add: 0, unit: "mA", group: "" },
            { symbol: "ekp_tv", name: "Fuel pump duty", offset: 73, format: 'uint16', scale: 0.00321, add: 0, unit: "ms", group: "" },
            { symbol: "lls_tv", name: "Idle actuator duty", offset: 75, format: 'uint16', scale: 0.02, add: 0, unit: "%", group: "" },
            { symbol: "md_llri", name: "Idle controller integrator", offset: 77, format: 'int15', scale: 0.1, add: 0, unit: "Nm", group: "" },
            { symbol: "fr_regler", name: "Filling controller", offset: 79, format: 'uint16', scale: 3.0517578125e-05, add: 0, unit: "", group: "" },
            { symbol: "edk_aus", name: "EGAS actuator duty", offset: 81, format: 'int15', scale: 0.05, add: 0, unit: "%tv", group: "" },
            { symbol: "can_fst", name: "CAN fuel level", offset: 83, format: 'uint8', scale: 1, add: 0, unit: "l", group: "" },
            { symbol: "ldp_abbr_feucht", name: "Leak diagnosis wetness abort count", offset: 84, format: 'uint16', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ldp_flags", name: "Leak test status flags", offset: 86, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "ldp_flags_nv", name: "Stored leak test status flags", offset: 87, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "tefc_ed", name: "TEV check diagnostic status", offset: 88, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "la_freeze_flag", name: "Lambda freeze-frame status", offset: 89, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
        ],
    },
    {
        selection: 21,
        name: "Rough Running System Check",
        group: "Misfire / Roughness",
        expectedLength: 42,
        fields: [
            { symbol: "ll_abw1", name: "Rough running cylinder 1", offset: 30, format: 'int15', scale: 0.001525878906, add: 0, unit: "%", group: "" },
            { symbol: "ll_abw2", name: "Rough running cylinder 2", offset: 32, format: 'int15', scale: 0.001525878906, add: 0, unit: "%", group: "" },
            { symbol: "ll_abw3", name: "Rough running cylinder 3", offset: 34, format: 'int15', scale: 0.001525878906, add: 0, unit: "%", group: "" },
            { symbol: "ll_abw4", name: "Rough running cylinder 4", offset: 36, format: 'int15', scale: 0.001525878906, add: 0, unit: "%", group: "" },
            { symbol: "ll_abw5", name: "Rough running cylinder 5", offset: 38, format: 'int15', scale: 0.001525878906, add: 0, unit: "%", group: "" },
            { symbol: "ll_abw6", name: "Rough running cylinder 6", offset: 40, format: 'int15', scale: 0.001525878906, add: 0, unit: "%", group: "" },
        ],
    },
    {
        selection: 35,
        name: "VANOS/CSL Measurements",
        group: "VANOS/CSL",
        expectedLength: 39,
        fields: [
            { symbol: "n", name: "Engine speed", offset: 0, format: 'uint16', scale: 1, add: 0, unit: "rpm", group: "VANOS" },
            { symbol: "evan1_ist", name: "Intake VANOS bank 1 actual", offset: 2, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "evan1_soll", name: "Intake VANOS bank 1 target", offset: 4, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "avan1_ist", name: "Exhaust VANOS bank 1 actual", offset: 6, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "avan1_soll", name: "Exhaust VANOS bank 1 target", offset: 8, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "evan2_ist", name: "Intake VANOS bank 2 actual", offset: 10, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "evan2_soll", name: "Intake VANOS bank 2 target", offset: 12, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "avan2_ist", name: "Exhaust VANOS bank 2 actual", offset: 14, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "avan2_soll", name: "Exhaust VANOS bank 2 target", offset: 16, format: 'int15', scale: 0.1, add: 0, unit: "°KW", group: "VANOS" },
            { symbol: "gks", name: "CSL snorkel flap position", offset: 18, format: 'uint16', scale: 1, add: 0, unit: "", group: "CSL" },
            { symbol: "gks_roh", name: "CSL snorkel flap position (raw)", offset: 20, format: 'uint10', scale: 0.00564, add: 0, unit: "V", group: "CSL" },
            { symbol: "psau_local", name: "Manifold Absolute Pressure (unfiltered)", offset: 22, format: 'uint16', scale: 0.03125, add: 0, unit: "mbar", group: "CSL" },
            { symbol: "psau_roh", name: "Manifold Absolute Pressure (raw)", offset: 24, format: 'uint10', scale: 0.00564, add: 0, unit: "V", group: "CSL" },
            { symbol: "dr_rel", name: "Relative Throttle", offset: 26, format: 'uint16', scale: 0.0030517578125, add: 0, unit: "%", group: "CSL" },
            { symbol: "rf_psau", name: "Relative Filling from MAP sensor", offset: 29, format: 'uint8', scale: 0.001, add: 0, unit: "-", group: "CSL" },
            { symbol: "rf_drrel", name: "Relative Filling from AlphaN", offset: 30, format: 'uint16', scale: 0.001, add: 0, unit: "-", group: "CSL" },
            { symbol: "rf_diag_f", name: "Relative Filling diagnosis filter", offset: 32, format: 'uint16', scale: 0.001, add: 0, unit: "-", group: "CSL" },
            { symbol: "rf_diag_f_max", name: "Relative Filling diagnosis filter max", offset: 34, format: 'uint16', scale: 0.001, add: 0, unit: "-", group: "CSL" },
            { symbol: "rf_diag_f_min", name: "Relative Filling diagnosis filter min", offset: 36, format: 'int15', scale: 0.001, add: 0, unit: "-", group: "CSL" },
            { symbol: "rf_diag_st", name: "Relative Filling diagnosis status", offset: 38, format: 'uint8', scale: 1, add: 0, unit: "", group: "CSL" },
        ],
    },
    {
        selection: 83,
        name: "EGAS Measurements",
        group: "EGAS",
        expectedLength: 52,
        fields: [
            { symbol: "freeze_flag", name: "EGAS event counter", offset: 0, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "sk_zustand_neu", name: "Fault severity / limp mode", offset: 1, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "pdr_zustand", name: "EGAS pre-drive check", offset: 2, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "zustand_motor", name: "Engine operating state", offset: 3, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "wdk1", name: "Throttle 1 position", offset: 4, format: 'uint16', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "wdk2", name: "Throttle 2 position", offset: 6, format: 'uint16', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "wdk1_abs", name: "Throttle pot 1 absolute voltage", offset: 8, format: 'uint16', scale: 0.004887585532746823, add: 0, unit: "V", group: "" },
            { symbol: "wdk2_abs", name: "Throttle pot 2 absolute voltage", offset: 10, format: 'uint16', scale: 0.004887585532746823, add: 0, unit: "V", group: "" },
            { symbol: "egas_soll", name: "Throttle target position", offset: 12, format: 'uint16', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "edk_aus", name: "EGAS actuator duty", offset: 14, format: 'int15', scale: 0.05, add: 0, unit: "%", group: "" },
            { symbol: "wdk_mode", name: "Throttle sensing state", offset: 16, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "wdk_adapt", name: "Throttle adaptation status", offset: 17, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "n40", name: "Engine speed", offset: 18, format: 'uint8', scale: 40, add: 0, unit: "rpm", group: "" },
            { symbol: "d_n40", name: "Engine speed gradient", offset: 19, format: 'int7', scale: 40, add: 0, unit: "rpm/s", group: "" },
            { symbol: "d_pwg", name: "Pedal value gradient", offset: 20, format: 'int15', scale: 0.1, add: 0, unit: "%/20ms", group: "" },
            { symbol: "d_wdk", name: "Throttle gradient", offset: 22, format: 'int15', scale: 5, add: 0, unit: "%/s", group: "" },
            { symbol: "t_ml", name: "Engine running time", offset: 24, format: 'uint16', scale: 1, add: 0, unit: "s", group: "" },
            { symbol: "ml", name: "Air mass", offset: 26, format: 'uint16', scale: 0.25, add: 0, unit: "kg/h", group: "" },
            { symbol: "ml_ersatz", name: "Air mass substitute/model", offset: 28, format: 'uint16', scale: 0.25, add: 0, unit: "kg/h", group: "" },
            { symbol: "rf", name: "Relative filling", offset: 30, format: 'uint16', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "pwg_soll", name: "Pedal target", offset: 32, format: 'uint16', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "md_ind_wunsch", name: "Driver requested torque", offset: 34, format: 'uint16', scale: 0.1, add: 0, unit: "Nm", group: "" },
            { symbol: "md_ind_wunsch_red_korr", name: "Filling torque request", offset: 36, format: 'uint16', scale: 0.1, add: 0, unit: "Nm", group: "" },
            { symbol: "md_ind_ne", name: "Actual torque after intervention", offset: 38, format: 'uint16', scale: 0.1, add: 0, unit: "Nm", group: "" },
            { symbol: "md_ind_opt_korr", name: "Actual torque", offset: 40, format: 'uint16', scale: 0.1, add: 0, unit: "Nm", group: "" },
            { symbol: "v_antrieb", name: "Rear-axle average speed", offset: 42, format: 'uint16', scale: 0.0625, add: 0, unit: "km/h", group: "" },
            { symbol: "asc_st", name: "Torque intervention request", offset: 44, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "fgr_b_aktiv", name: "Cruise-control status", offset: 45, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "pwg_mode", name: "Pedal sensing state", offset: 46, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "edksi_zustand", name: "EGAS target/actual comparison state", offset: 47, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "md_dyn_st", name: "Dynamic filter status", offset: 48, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "gang", name: "Calculated gear", offset: 49, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "s_krafts", name: "Powertrain engaged status", offset: 50, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
            { symbol: "sa_we_st", name: "Overrun fuel cutoff calculation status", offset: 51, format: 'uint8', scale: 1, add: 0, unit: "", group: "" },
        ],
    },
    {
        selection: 179,
        name: "Rough Running",
        group: "Misfire / Roughness",
        expectedLength: 16,
        fields: [
            { symbol: "lu[0]", name: "Segment time deviation cylinder 1", offset: 0, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "lu[1]", name: "Segment time deviation cylinder 2", offset: 2, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "lu[2]", name: "Segment time deviation cylinder 3", offset: 4, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "lu[3]", name: "Segment time deviation cylinder 4", offset: 6, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "lu[4]", name: "Segment time deviation cylinder 5", offset: 8, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
            { symbol: "lu[5]", name: "Segment time deviation cylinder 6", offset: 10, format: 'int15', scale: 0.1, add: 0, unit: "%", group: "" },
        ],
    },
];

export const MSS54_LIVE_FIELD_COUNT = 213;
