#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""MSS54 (S54 エンジン) の手書き説明。

SYSTEMCHECK 群を含む。この 11 件は旧アプリで**完全に不可視**だった一方、
二次空気・タンクリーク・DMTL・TEV は車検の排ガス項目と警告灯でオーナーが
実際に困る場所そのものである。しかも ECU が判定文の語彙表
(`SLSSTATUS` / `LDPSTATUS` / `TEVSTATUS`) を自分で持っている。
"""
from __future__ import annotations

MSS54: dict[str, dict[str, tuple[str, str]]] = {
    # ------------------------------------------------------ 故障メモリ書込
    "FS_LOESCHEN": {
        "does": ("DME が記録している故障コードをすべて消します。フリーズフレーム（そのときの回転数・水温・負荷など）も一緒に消えます。",
                 "Erases every fault code the DME has stored, along with the freeze frames that captured engine speed, coolant temperature and load at the time."),
        "observe": ("車では何も起きません。チェックランプが点いていた場合、原因が直っていれば消え、直っていなければ走行後すぐ再点灯します。",
                    "Nothing happens on the car. If the check lamp was on it goes out - and comes back shortly after you drive if the cause is still present."),
        "pass": ("消去後に読み直して空、さらに一度走ってから読み直しても空なら、本当に直っています。",
                 "Read back empty, then drive and read again: still empty means it is genuinely fixed."),
        "fail": ("すぐ戻るコードは現在進行形の故障です。**消すことは修理ではありません。** 戻ってきたコードとそのフリーズフレームが、直すべき対象そのものです。",
                 "A code that returns quickly is a live fault. **Erasing is not repairing.** The code that comes back, and its freeze frame, is the thing to fix."),
        "after": ("故障履歴とフリーズフレームが失われます。**フリーズフレームは「どういう条件で起きたか」の唯一の手がかりです。** 消す前に必ず控えてください。",
                  "The history and its freeze frames are gone. **A freeze frame is the only record of the conditions the fault occurred under.** Note it before erasing."),
        "caution": ("排ガス関連のレディネスコードもリセットされ、車検に必要な走行条件を満たし直す必要が出る場合があります。",
                    "Emissions readiness monitors reset too, which can mean re-driving the cycles an inspection requires."),
    },
    "FS_SELEKTIV_LOESCHEN": {
        "does": ("指定した故障コードだけを消します。他のコードと履歴は残ります。",
                 "Erases only the fault codes you name. Everything else stays."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("指定したコードだけが消え、他が残っていれば成功です。",
                 "Success is: the named codes gone, the rest still there."),
        "fail": ("消えない場合は、そのコードが今この瞬間も立ち続けています。",
                 "A code that will not clear is one the ECU is still setting right now."),
        "after": ("消したコードの履歴とフリーズフレームは戻りません。",
                  "The erased codes and their freeze frames do not come back."),
    },
    # ------------------------------------------------------------ 学習値系
    "ADAPT_LOESCHEN": {
        "does": ("DME が走行中に学習したすべての補正値を初期値に戻します。燃料補正・アイドル学習・スロットル学習・クランクホイール補正などが対象です。",
                 "Resets every correction the DME has learned while driving: fuel trim, idle, throttle and crank-wheel adaptations among them."),
        "observe": ("車では何も起きません。次にエンジンを掛けたときから挙動が変わります。",
                    "Nothing happens on the car. The difference appears the next time you start it."),
        "pass": ("消去後、アイドルが安定し、走行を重ねるにつれて燃料補正値が妥当な範囲に収束していけば成功です。",
                 "Success is: the idle settles, and over the following drives the fuel trims converge back to sensible values."),
        "fail": ("学習し直しても以前と同じところに戻る場合、それは学習のずれではなく**実際の不具合**です。二次エア吸い・インジェクタの汚れ・O2センサの劣化を疑ってください。",
                 "If the trims learn straight back to where they were, that is not a stale adaptation - it is a **real fault**. Suspect an air leak, dirty injectors or a tired O2 sensor."),
        "after": ("**しばらくは調子が変わります。** アイドルが不安定になったり、燃費が一時的に悪化したりします。数十kmから数百kmの走行で学習し直します。学習前の値はこのアプリからは復元できません。",
                  "**The car will run differently for a while** - an unsettled idle, temporarily worse economy. It re-learns over tens to hundreds of kilometres. The previous values cannot be restored from here."),
        "caution": ("原因を調べずに消すと、症状だけが一時的に隠れて再発します。消す前に学習値を読んで控えてください。",
                    "Clearing without investigating hides the symptom temporarily and it returns. Read and note the values before clearing."),
    },
    "ADAPT_SELEKTIV_LOESCHEN": {
        "does": ("学習値をビット単位で選んで消します。どのビットが何に対応するかは引数 `STATUS_ADAPT` で指定します。",
                 "Clears learned values selectively, bit by bit. Which bit means what is chosen through the STATUS_ADAPT argument."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("狙った学習値だけが初期値に戻り、他が残っていれば成功です。消去後に学習値を読んで確認してください。",
                 "Success is: the targeted values back at default and the rest untouched. Read the adaptations back to confirm."),
        "fail": ("**ビットの割当を間違えると、意図しない学習値を消します。** どのビットが何かを SGBD の引数説明で確認してから実行してください。",
                 "**Getting the bit assignment wrong clears something you did not mean to.** Confirm what each bit is from the SGBD argument description before running it."),
        "after": ("消した学習値は走行で学習し直すまで初期値のままです。復元はできません。",
                  "What you cleared stays at default until the car re-learns it. There is no restore."),
    },
    "ADAPT_GERAEUSCHKLAPPE": {
        "does": ("吸気ノイズフラップを開いて、その位置を学習させます。フラップの機械的な可動範囲を DME に教える操作です。",
                 "Opens the intake noise flap and learns its position, teaching the DME the flap's mechanical travel."),
        "observe": ("フラップが動く音がします。",
                    "You will hear the flap move."),
        "pass": ("学習後、フラップ位置の読み値が可動範囲全体をカバーしていれば成功です。",
                 "Success is: afterwards the learned position covers the full travel."),
        "fail": ("動かない場合はリンケージの固着かモータ不良です。学習値が極端な場合はフラップが途中で引っかかっています。",
                 "No movement means seized linkage or a dead motor. An extreme learned value means the flap is catching part-way."),
        "after": ("学習した位置が保存されます。リンケージを整備したあとは取り直しが必要です。",
                  "The learned position is stored. Retake it after any work on the linkage."),
    },
    # ------------------------------------------------------------ ECU 操作
    "SG_RESET": {
        "does": ("DME をソフトウェアリセットします。SGBD 自身が「適応値と故障メモリは保存されない」と警告しています。",
                 "Software-resets the DME. The SGBD itself warns that adaptations and the fault memory are not preserved."),
        "observe": ("エンジンが掛かっている場合は停止します。実行中は一時的に通信も切れます。",
                    "If the engine is running it stops. Communication drops briefly while it resets."),
        "pass": ("リセット後に DME が正常に立ち上がり、通信が戻り、エンジンが始動すれば成功です。",
                 "Success is: the DME comes back up, communication returns and the engine starts."),
        "fail": ("立ち上がらない場合は電源電圧を確認してください。リセット中の電圧降下は最悪の事態を招きます。",
                 "If it does not come back, check the supply voltage. A voltage drop during a reset is the worst case."),
        "after": ("**適応値と故障メモリが保存されない可能性があります**（SGBD の原文どおり）。学習し直すまで挙動が変わります。",
                  "**Adaptations and fault memory may not survive** - that is the SGBD's own wording. The car runs differently until it re-learns."),
        "caution": ("エンジン停止・電圧安定を確認してから実行してください。",
                    "Only with the engine stopped and the supply steady."),
    },
    "EDIC_RESET": {
        "does": ("EDIC（診断インタフェース側の設定）をリセットします。",
                 "Resets EDIC - the diagnostic interface settings."),
        "observe": ("車では何も起きません。診断通信が一時的に切れることがあります。",
                    "Nothing happens on the car. The diagnostic link may drop briefly."),
        "pass": ("リセット後に通信が復帰すれば成功です。",
                 "Success is communication coming back."),
        "fail": ("復帰しない場合はイグニッションを入れ直して再接続してください。",
                 "If it does not, cycle the ignition and reconnect."),
        "after": ("診断通信の設定が初期値に戻ります。車両の走行には影響しません。",
                  "Diagnostic link settings return to default. It does not affect how the car drives."),
    },
    "INITIALISIERUNG": {
        "does": ("DME を初期状態へ戻します。学習値が初期値に戻ります。",
                 "Returns the DME towards its initial state. Learned values go back to defaults."),
        "observe": ("車では何も起きません。次の始動から挙動が変わります。",
                    "Nothing happens on the car. The difference shows from the next start."),
        "pass": ("初期化後にエンジンが正常に始動し、アイドルが安定すれば成功です。",
                 "Success is: it starts normally afterwards and the idle settles."),
        "fail": ("アイドルが安定しない場合は、学習で隠れていた不具合が表に出た可能性があります。二次エア吸いとスロットルの汚れを見てください。",
                 "An unsettled idle can mean a fault the adaptations were masking has surfaced. Check for air leaks and dirty throttle bodies."),
        "after": ("**学習値が失われます。** 走行で学習し直すまで、アイドルや燃費が普段と違います。",
                  "**Learned values are gone.** Idle and economy will be off until the car re-learns them."),
    },
    # ------------------------------------------------------------ 工場調整値
    "ABGLEICHWERTE_SCHREIBEN": {
        "does": ("工場でこのエンジン個体に合わせて書かれた調整値を書き換えます。学習値とは別物で、走行では変わらない値です。",
                 "Rewrites the calibration values the factory wrote for this specific engine. These are not learned values; driving does not change them."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("書込後に `ABGLEICHWERTE_LESEN` で読み戻し、意図した値になっていれば成功です。",
                 "Success is: read it back with ABGLEICHWERTE_LESEN and find what you intended."),
        "fail": ("拒否される場合は `ABGLEICH_LOGIN_REQUEST` による保護解除が済んでいません。",
                 "A refusal means the protection has not been unlocked with ABGLEICH_LOGIN_REQUEST."),
        "after": ("**エンジン個体に紐づく値を書き換えます。取り消しはできません。** 書く前に必ず `ABGLEICHWERTE_LESEN` で現在値を読み出し、保存してください。誤った値は混合気や制御の基準そのものを狂わせます。",
                  "**You are overwriting values tied to this specific engine, and there is no undo.** Read the current values with ABGLEICHWERTE_LESEN and save them first. Wrong values corrupt the reference the mixture and control are built on."),
        "caution": ("元の値を保存せずに実行しないでください。このアプリは以前の値を復元できません。",
                    "Do not run this without saving the current values. Nothing here can restore them."),
    },
    "ABGLEICHFLAG_SCHREIBEN": {
        "does": ("工場調整値が有効かどうかを示すフラグを書き換えます。",
                 "Writes the flag that says whether the factory calibration values are valid."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("書込後にフラグを読み戻して、意図した状態になっていれば成功です。",
                 "Success is: read the flag back and find what you intended."),
        "fail": ("拒否される場合は保護解除が済んでいません。",
                 "A refusal means the protection is not unlocked."),
        "after": ("**フラグを無効側にすると、DME が調整値を使わなくなります。** 調整値本体を書き換えるより影響が大きい場合があります。",
                  "**Setting it invalid makes the DME stop using the calibration values at all**, which can matter more than changing the values themselves."),
    },
    "CO_EINZELABGLEICH_VERSTELLEN": {
        "does": ("排ガスの CO 調整値を **RAM 上で** 変更します。この操作だけでは恒久的に残りません。",
                 "Changes the CO trim **in RAM only**. This step alone does not persist."),
        "observe": ("エンジンが掛かっていれば、混合気が変わって回転や排気の匂いが変わることがあります。",
                    "With the engine running you may notice the mixture change - idle note, exhaust smell."),
        "pass": ("排ガステスタの CO 値が狙いに入れば成功です。",
                 "Success is the CO reading on the gas analyser landing where you want it."),
        "fail": ("値を動かしても CO が変わらない場合、CO 調整以外の要因（二次エア吸い、O2センサ、触媒）です。",
                 "If moving the value does not move the CO, the cause is elsewhere: an air leak, the O2 sensor, or the catalyst."),
        "after": ("**RAM 上の変更なので、イグニッションを切ると失われます。** 恒久化するには `CO_EINZELABGLEICH_PROGRAMMIEREN` が必要です。逆に言うと、この段階なら電源を落とせば元に戻せます。",
                  "**Being in RAM, it is lost at ignition off.** Making it permanent needs CO_EINZELABGLEICH_PROGRAMMIEREN. The upside is that at this stage, switching off undoes it."),
    },
    "CO_EINZELABGLEICH_PROGRAMMIEREN": {
        "does": ("RAM 上で調整した CO 値を **EEPROM に焼き込みます**。ここで初めて恒久的になります。",
                 "Burns the CO value adjusted in RAM **into EEPROM**. This is the step that makes it permanent."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("書込後にイグニッションを切って入れ直し、値が残っていれば成功です。",
                 "Success is: cycle the ignition and find the value still there."),
        "fail": ("書込に失敗した場合、EEPROM の該当セルが消去されていないか、電圧が不足しています。",
                 "A failed write means the EEPROM cell was not erased, or the supply sagged."),
        "after": ("**EEPROM への書込であり、イグニッションを切っても残ります。取り消しはできません。** 焼く前に、RAM 上の値で排ガス測定が本当に狙いどおりかを確認してください。",
                  "**This is an EEPROM write. It survives ignition off and cannot be undone.** Confirm on the analyser that the RAM value is genuinely right before burning it."),
        "caution": ("EEPROM の書込回数には限りがあります。試行錯誤は RAM 側 (`_VERSTELLEN`) で行ってください。",
                    "EEPROM endurance is finite. Do the trial and error in RAM with _VERSTELLEN."),
    },
    # ------------------------------------------------------------ イモビ
    "EWS3_INITIALISIEREN": {
        "does": ("イモビライザ(EWS)を初期化し、DME と EWS の対応付けをやり直します。",
                 "Initialises the immobiliser (EWS) and re-establishes the pairing between the DME and EWS."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("初期化後に `EWS3_GET_STATUS` で同期済みと出て、エンジンが始動すれば成功です。",
                 "Success is: EWS3_GET_STATUS reports synchronised and the engine starts."),
        "fail": ("同期しない場合、鍵・EWS・DME のいずれかが他の車両のものである可能性があります。**この状態ではエンジンが始動しません。**",
                 "Failure to synchronise can mean the key, the EWS or the DME belongs to a different car. **The engine will not start in this state.**"),
        "after": ("**失敗するとエンジンが始動しなくなります。** 復旧には正しい鍵と、場合によっては BMW の認証が必要です。",
                  "**A failure leaves the car unable to start.** Recovery needs the correct key and possibly BMW authorisation."),
        "caution": ("盗難防止機構に触る操作です。実行前に、正しい鍵が手元にあることを確認してください。",
                    "This touches the anti-theft system. Confirm you have the correct key in hand before running it."),
    },
    "EWS3_SYNC": {
        "does": ("EWS 制御ユニットをリセットして、DME との同期を取り直します。",
                 "Resets the EWS control unit and re-synchronises it with the DME."),
        "observe": ("車では何も起きません。",
                    "Nothing happens on the car."),
        "pass": ("同期後にエンジンが始動すれば成功です。",
                 "Success is the engine starting afterwards."),
        "fail": ("始動しない場合、鍵と EWS の対応か、EWS と DME の対応が取れていません。",
                 "If it will not start, either the key and EWS or the EWS and DME are not paired."),
        "after": ("**同期に失敗した状態ではエンジンが始動しません。**",
                  "**With synchronisation failed, the engine will not start.**"),
        "caution": ("正しい鍵が手元にあることを確認してから実行してください。",
                    "Confirm you have the correct key before running it."),
    },
    # ------------------------------------------------------ プログラミング系
    "SPEICHER_SCHREIBEN": {
        "does": ("ECU の任意のメモリアドレスに直接書き込みます。**このアプリからは実行しません。**",
                 "Writes directly to an arbitrary ECU memory address. **This app does not run it.**"),
        "observe": ("このアプリでは実行できないため、何も起きません。",
                    "Nothing happens, because this app will not run it."),
        "pass": ("該当しません。",
                 "Not applicable."),
        "fail": ("該当しません。",
                 "Not applicable."),
        "after": ("誤ったアドレスへの書込は ECU を起動不能にします。この領域は WinKFP など専用ツールの担当で、復旧にはベンチでの書き戻しが要ります。",
                  "A write to the wrong address leaves the ECU unable to boot. This is WinKFP territory, and recovery means writing it back on a bench."),
    },
    "SPEICHER_SCHREIBEN_BINAER": {
        "does": ("ECU のメモリにバイナリを直接書き込みます。**このアプリからは実行しません。**",
                 "Writes a binary blob directly into ECU memory. **This app does not run it.**"),
        "observe": ("このアプリでは実行できないため、何も起きません。",
                    "Nothing happens, because this app will not run it."),
        "pass": ("該当しません。", "Not applicable."),
        "fail": ("該当しません。", "Not applicable."),
        "after": ("フラッシュ書換と同じ危険度です。専用ツールと、失敗したときに書き戻せる手段を用意してから行う作業です。",
                  "As dangerous as a flash write. It belongs to dedicated tooling, and to people who already have a way to write it back."),
    },
    # ------------------------------------------------------- SYSTEMCHECK 11件
    # 旧アプリでは1件も見えていなかった。二次空気・タンクリーク・DMTL・TEV は
    # 車検の排ガス項目とチェックランプでオーナーが実際に困る場所そのもので、
    # しかも ECU が判定文の語彙表を自分で持っている
    # (SLSSTATUS 6行 / LDPSTATUS 59行 / TEVSTATUS 20行)。
    "START_SYSTEMCHECK_SEK_LUFT": {
        "does": ("二次空気システムの検査を開始します。冷間始動直後に排気側へ空気を送って触媒を早く暖める仕組みが、実際に空気を送れているかを ECU が自分で調べます。",
                 "Starts the secondary-air test. The system that pumps air into the exhaust after a cold start to warm the catalyst gets checked, by the ECU, for whether it actually moves air."),
        "observe": ("エンジンルームからポンプの作動音がします。数十秒続きます。",
                    "You will hear the pump run in the engine bay, for some tens of seconds."),
        "pass": ("`LESEN_SYSTEMCHECK_SEK_LUFT` で結果を読み、`1_SLS_OK` が返れば正常です。",
                 "Read the result with LESEN_SYSTEMCHECK_SEK_LUFT: 1_SLS_OK means the system is good."),
        "fail": ("`2_SLS_FEHLER` なら、ポンプが回っていないか、ポンプは回っても空気が排気側に届いていません。ポンプ本体・切替弁・ホースの詰まりの順で見てください。二次空気は冷間時しか動かないので、暖機後に確認しても何も分かりません。",
                 "2_SLS_FEHLER means either the pump is not running, or it runs but the air is not reaching the exhaust. Check the pump, then the changeover valve, then the hoses for blockage. Secondary air only runs cold, so checking a warm engine tells you nothing."),
        "after": ("検査が走り続けます。**`LESEN_SYSTEMCHECK_SEK_LUFT` を実行するまで完了しません。** 中断したい場合は `STOP_SYSTEMCHECK_SEK_LUFT` を送ってください。",
                  "The test keeps running. **It is not finished until you run LESEN_SYSTEMCHECK_SEK_LUFT.** To abort, send STOP_SYSTEMCHECK_SEK_LUFT."),
        "caution": ("エンジンが冷えている状態でないと、検査条件を満たしません。",
                    "The engine has to be cold or the test conditions are not met."),
    },
    "STOP_SYSTEMCHECK_SEK_LUFT": {
        "does": ("走っている二次空気検査を中断します。",
                 "Aborts a running secondary-air test."),
        "observe": ("ポンプの音が止まります。", "The pump goes quiet."),
        "pass": ("ポンプが止まれば成功です。", "Success is the pump stopping."),
        "fail": ("止まらない場合はイグニッションを切ってください。",
                 "If it does not stop, cycle the ignition."),
        "after": ("検査結果は得られません。判定が要る場合は最初からやり直してください。",
                  "You get no result. If you need a verdict, start again from the beginning."),
    },
    "LESEN_SYSTEMCHECK_SEK_LUFT": {
        "does": ("`START_SYSTEMCHECK_SEK_LUFT` で始めた二次空気検査の結果を受け取ります。",
                 "Collects the result of the secondary-air test started by START_SYSTEMCHECK_SEK_LUFT."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("`1_SLS_OK` が正常です。", "1_SLS_OK is the good result."),
        "fail": ("`0 ABBRUCH_GRUNDZUSTAND` は検査が始まってすらいません。開始ジョブを先に実行してください。`2_SLS_FEHLER` は実際の不具合です。",
                 "0 ABBRUCH_GRUNDZUSTAND means the test never started - run the start job first. 2_SLS_FEHLER is a real fault."),
        "after": ("何も変わりません。", "Nothing changes."),
    },
    "START_SYSTEMCHECK_TANK_LECK": {
        "does": ("燃料タンクと蒸発ガス配管の気密検査を開始します。DMTL がタンクをわずかに加圧し、圧力の抜け方から漏れの有無と大きさを判定します。",
                 "Starts the fuel-tank and evaporative-system leak test. The DMTL pressurises the tank slightly and judges from how the pressure decays whether there is a leak and how big."),
        "observe": ("右後輪の内側あたりから小さなポンプ音がします。検査には数分かかります。",
                    "A small pump runs near the right rear wheel arch. It takes several minutes."),
        "pass": ("`LESEN_SYSTEMCHECK_TANK_LECK` で結果を読み、漏れなしと出れば正常です。",
                 "Read the result with LESEN_SYSTEMCHECK_TANK_LECK: no leak is the good outcome."),
        "fail": ("漏れが検出された場合、**まず燃料キャップを確認してください。** 最も多い原因です。次にタンク周りのホース、キャニスタ、DMTL 本体の順です。",
                 "If a leak is reported, **check the fuel cap first** - it is by far the most common cause. Then the hoses around the tank, the canister, and the DMTL itself."),
        "after": ("検査が走り続けます。**結果読取ジョブを実行するまで完了しません。**",
                  "The test keeps running. **It is not finished until you run the result-read job.**"),
        "caution": ("燃料残量が多すぎても少なすぎても検査条件を満たしません。実行中は給油しないでください。",
                    "The test will not run with the tank too full or too empty. Do not refuel while it runs."),
    },
    "LESEN_SYSTEMCHECK_TANK_LECK": {
        "does": ("タンク気密検査の結果を受け取ります。",
                 "Collects the result of the tank leak test."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("漏れなしと出れば正常です。", "No leak reported is the good outcome."),
        "fail": ("`0 ABBRUCH_GRUNDZUSTAND` は検査が始まっていません。漏れありの場合は燃料キャップから確認してください。",
                 "0 ABBRUCH_GRUNDZUSTAND means the test never started. If a leak is reported, start with the fuel cap."),
        "after": ("何も変わりません。", "Nothing changes."),
    },
    "START_SYSTEMCHECK_DMTL": {
        "does": ("DMTL（タンク漏れ診断モジュール）そのものが正常に働くかを検査します。タンクの漏れではなく、**検査する装置の側**を調べます。",
                 "Tests whether the DMTL - the tank-leak diagnosis module - works at all. This checks the **device itself**, not the tank."),
        "observe": ("右後輪の内側あたりからポンプ音がします。",
                    "A pump runs near the right rear wheel arch."),
        "pass": ("`LESEN_SYSTEMCHECK_DMTL` で結果を読み、正常と出ればモジュール自体は健全です。",
                 "Read the result with LESEN_SYSTEMCHECK_DMTL: a good result means the module itself is healthy."),
        "fail": ("モジュール不良と出た場合、タンク漏れの検査結果は信用できません。**DMTL を直してからタンク検査をやり直してください。** 順序を逆にすると、装置の不良を漏れと誤診します。",
                 "If the module is faulty, no tank-leak result from it can be trusted. **Fix the DMTL, then redo the tank test.** The other order misdiagnoses a broken instrument as a leak."),
        "after": ("検査が走り続けます。**結果読取ジョブを実行するまで完了しません。**",
                  "The test keeps running. **It is not finished until you run the result-read job.**"),
    },
    "LESEN_SYSTEMCHECK_DMTL": {
        "does": ("DMTL 自己診断の結果を受け取ります。ECU は結果を平文の判定文でも返します。",
                 "Collects the DMTL self-test result. The ECU returns it as a plain-language verdict as well as a code."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("正常と出れば DMTL 自体は健全で、タンク漏れ検査の結果を信用できます。",
                 "A good result means the DMTL is healthy and its tank-leak results can be trusted."),
        "fail": ("`0 ABBRUCH_GRUNDZUSTAND` は検査が始まっていません。モジュール不良ならヒータ・ポンプ・切替弁のいずれかです。",
                 "0 ABBRUCH_GRUNDZUSTAND means it never started. A module fault is the heater, the pump or the changeover valve."),
        "after": ("何も変わりません。", "Nothing changes."),
    },
    "START_SYSTEMCHECK_DMTL_ECOS": {
        "does": ("DMTL の ECOS 版検査を開始します。**SGBD にこの検査の結果読取ジョブが存在しません。**",
                 "Starts the ECOS variant of the DMTL test. **The SGBD contains no result-read job for it.**"),
        "observe": ("ポンプ音がすることがあります。", "A pump may run."),
        "pass": ("結果を受け取る手段が SGBD に無いため、このアプリからは合否を示せません。",
                 "There is no way in the SGBD to collect the result, so nothing here can tell you pass or fail."),
        "fail": ("同上です。**結果を読めない検査を実車で実行する意味はほとんどありません。** 通常版の `START_SYSTEMCHECK_DMTL` を使ってください。",
                 "Likewise. **There is little point running a test on a car when you cannot read its result.** Use the ordinary START_SYSTEMCHECK_DMTL instead."),
        "after": ("検査が走ったまま残る可能性があります。",
                  "The test may be left running."),
    },
    "START_SYSTEMCHECK_TEV_FUNC": {
        "does": ("タンク通気弁(TEV)が指示どおり開閉するかを検査します。この弁はガソリン蒸気をエンジンに吸わせる経路の開閉を担当します。",
                 "Tests whether the tank vent valve (TEV) opens and closes as commanded. That valve gates the path by which fuel vapour is drawn into the engine."),
        "observe": ("弁の作動音がすることがあります。アイドルがわずかに変化する場合があります。",
                    "You may hear the valve click, and the idle may shift slightly."),
        "pass": ("`LESEN_SYSTEMCHECK_TEV_FUNC` で結果を読み、正常と出れば弁は生きています。",
                 "Read the result with LESEN_SYSTEMCHECK_TEV_FUNC: a good result means the valve is alive."),
        "fail": ("不良の場合、開いたまま固着していればアイドル不調と始動性悪化、閉じたまま固着していれば蒸発ガス系の警告灯として出ます。弁と、そこに繋がるホースを見てください。",
                 "Stuck open shows as a rough idle and hard starting; stuck closed shows as an evaporative-system warning lamp. Check the valve and the hoses to it."),
        "after": ("検査が走り続けます。**結果読取ジョブを実行するまで完了しません。**",
                  "The test keeps running. **It is not finished until you run the result-read job.**"),
    },
    "LESEN_SYSTEMCHECK_TEV_FUNC": {
        "does": ("タンク通気弁検査の結果を受け取ります。",
                 "Collects the result of the tank vent valve test."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("正常と出れば弁は指示どおり動いています。",
                 "A good result means the valve responds as commanded."),
        "fail": ("`0 ABBRUCH_GRUNDZUSTAND` は検査が始まっていません。不良なら弁の固着です。",
                 "0 ABBRUCH_GRUNDZUSTAND means it never started. A fault means the valve is stuck."),
        "after": ("何も変わりません。", "Nothing changes."),
    },
    "LESEN_SYSTEMCHECK_LAUFUNRUHE": {
        "does": ("回転変動（失火検出）の検査結果を受け取ります。クランクの回り方のムラから、どの気筒がどれだけ失火しているかを ECU が数えています。**対応する開始ジョブは SGBD にありません**——この検査は走行中に常時動いています。",
                 "Collects the running-roughness (misfire detection) result. The ECU counts, from unevenness in crankshaft rotation, which cylinder is misfiring and how much. **There is no matching start job** - this test runs continuously while you drive."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("全気筒の失火カウントが低ければ正常です。",
                 "Low misfire counts across all cylinders is the good outcome."),
        "fail": ("特定の気筒だけカウントが高い場合、その気筒の点火コイル・プラグ・インジェクタ・圧縮を順に見てください。全気筒に散っている場合は燃料圧やカム位置など全体に効く要因です。",
                 "A high count on one cylinder points to that cylinder's coil, plug, injector or compression. Counts spread across all of them point to something global: fuel pressure, cam position."),
        "after": ("何も変わりません。", "Nothing changes."),
    },
    "PRUEFSTEMPEL_LESEN": {
        "does": ("この ECU に記録されている検査スタンプを読み出します。",
                 "Reads the inspection stamps recorded in this ECU."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("記録が返れば成功です。内容は履歴で、現在の健康状態ではありません。",
                 "A record coming back is success. It is history, not present health."),
        "fail": ("読めない場合は通信の問題です。", "Failure to read is a communication problem."),
        "after": ("何も変わりません。", "Nothing changes."),
    },
    "PRUEFSTEMPEL_SCHREIBEN": {
        "does": ("検査スタンプを書き込みます。車の動作には影響しませんが、記録は書き換わります。",
                 "Writes an inspection stamp. It does not affect how the car runs, but the record changes."),
        "observe": ("車では何も起きません。", "Nothing happens on the car."),
        "pass": ("書込後に読み戻して意図した内容なら成功です。",
                 "Success is reading back what you intended."),
        "fail": ("拒否される場合は保護が解除されていません。",
                 "A refusal means the protection is not unlocked."),
        "after": ("**整備履歴の改変にあたります。** 元の内容は復元できません。書く前に読み出して控えてください。",
                  "**This alters a service record.** The previous content cannot be restored. Read and note it first."),
        "caution": ("車両の来歴に関する情報を変えることになります。",
                    "You are changing information about the car's history."),
    },
}
